name: publish_projectdb_on_release

on:
  release:
    types: [published]

jobs:
  publish_to_dockerhub:
    name: publish_projectdb_on_release_publish_to_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: publish_projectdb_on_release_publish_to_dockerhub_checkout
        uses: actions/checkout@v4

      - name: publish_projectdb_on_release_publish_to_dockerhub_login
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish_projectdb_on_release_publish_to_dockerhub_setenv
        run: echo "FLATTENED_TAG=${{ vars.DOCKER_REPO_PROJECTDB }}:release-$(git log -1 --format=%cd --date=format:%Y%m%dh%H%M%S)" >> $GITHUB_ENV

      - name: publish_projectdb_on_release_publish_to_dockerhub_buildandpublish
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.FLATTENED_TAG }}
