name: publish_projectdb_on_release

on:
  release:
    types: [published]

jobs:
  publish_to_dockerhub:
    name: publish_projectdb_on_release.publish_to_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: publish_projectdb_on_release.publish_to_dockerhub.checkout
        uses: actions/checkout@v4

      - name: publish_projectdb_on_release.publish_to_dockerhub.login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish_projectdb_on_release.publish_to_dockerhub.setenv
        run: echo "FLATTENED_TAG=${{ vars.DOCKER_REPO }}:release-$(git log -1 --format=%cd --date=format:%Y%m%dh%H%M%S)" >> $GITHUB_ENV

      - name: publish_projectdb_on_release.publish_to_dockerhub.buildandpublish
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.FLATTENED_TAG }}
