# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ruby.build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: ruby.build.checkout
        uses: actions/checkout@v3
      - name: ruby.build.rubysetup
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: ruby.build.dbsetup
        run: bin/rails db:prepare
      # - name: Run tests
      #  run: bin/rake

  ruby.lint:
    runs-on: ubuntu-latest
    steps:
      - name: ruby.lint.checkout
        uses: actions/checkout@v3
      - name: ruby.lint.rubysetup
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: ruby.lint.bundleraudit
        run: bundle exec bundler-audit --update
      - name: ruby.lint.brakeman
        run: bundle exec brakeman -q -w2
      - name: ruby.lint.rubocop
        run: bundle exec rubocop --require rubocop-rails --parallel
